version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: appForm
      POSTGRES_USER: form
      POSTGRES_PASSWORD: testeForm
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./db/postgres/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appForm
      POSTGRES_USER: form
      POSTGRES_PASSWORD: testeForm